from .config import get_config
import json

config = get_config()
FILENAME = config['RAMDISK_DIR'] + "execute.lua"

def write_addresses(addresses_json):
	"""
	Generate a Lua script from an addresses payload and write it to execute.lua.
	`addresses_json` may be a dict, list, or JSON string. Returns (message, status_code).
	"""
	if addresses_json is None:
		return "Missing addresses", 400
	
	addresses = addresses_json

	# Normalize to a list of dicts
	addresses_list = []
	if isinstance(addresses, dict):
		addresses_list.append(addresses)
	elif isinstance(addresses, list):
		for item in addresses:
			if not isinstance(item, dict):
				return "addresses list must contain objects mapping address->value", 400
			addresses_list.append(item)
	else:
		return "addresses must be an object or list of objects", 400

	script_lines = ["-- Generated by ffbot /nes/write endpoint"]

	for addr_map in addresses_list:
		for addr, val in addr_map.items():
			addr_literal = addr
			if isinstance(addr, str):
				addr_strip = addr.strip()
				if addr_strip.lower().startswith('0x'):
					addr_literal = addr_strip
				else:
					addr_literal = addr_strip
			else:
				addr_literal = str(addr)

			val_literal = None
			if isinstance(val, str):
				v = val.strip()
				try:
					if v.lower().startswith('0x'):
						val_literal = str(int(v, 16))
					else:
						val_literal = str(int(v))
				except Exception:
					val_literal = f'"{v}"'
			else:
				val_literal = str(val)

			script_lines.append(f"memory.writebyte({addr_literal}, {val_literal})")

	lua_script = "\n".join(script_lines) + "\n"

	try:
		with open(FILENAME, 'w') as f:
			f.write(lua_script)
		return f"'{FILENAME}' written successfully", 200
	except Exception as e:
		return f"Error writing file: {e}", 500


__all__ = ["write_addresses"]
